### PR TITLE
Feat/UI and rewards api

### LINKED ISSUE #9: Sheet home card
### Reason

Create the sheet home

### Description

image

- Month and lifetime values are variable inputs
- The circular progress bar reflects the month values 

### Success Criteria

- [x] criteria 1

### Additional Information

_No response_

### LINKED ISSUE #10: Sheet home carousel
### Reason

Create the sheet home

### Description

Create a carousel with all the accounts available for login.
The carousel items should come from an enum that holds the name, ID to be used for login, and icon.

Captura de Tela 2023-10-31 às 18 19 31

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #11: Sheet home account grid
### Reason

Create the sheet home

### Description

when the user scrolls up the account carousel, the bottom sheet should expand and show all the accounts in a grid

Captura de Tela 2023-10-31 às 18 21 41

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #12: More Sheet
### Reason

Create the more sheet UI

### Description

When the user taps in the "more" word in sheet home, open the "More Sheet"

- The monthly estimate comes from a list where the top 3 will be the green bars, darker, medium and lighter and the others will be the white part.
- Connected accounts are shown in a grid. if the account is not verified it should show a red exclamation icon on top.
- Report an issue should be a tappable link. Action TBD
- Data licensing agreement should show the terms
- Opt out should revoke the license

image

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### LINKED ISSUE #13: Create the email account screen
### Reason

Create the email account screen for connecting an email account

### Description

This sheet should be opened when the user taps on an email account in the home sheet.
- for Gmail and outlook add the OAuth sign in button.

image

### Success Criteria

- [ ] UI meets the specs

### Additional Information

_No response_

### LINKED ISSUE #14: Create the Retailer account screen
### Reason

Create the retailer account screen

### Description

No account connected
image

One account connected:
image

### Success Criteria

- [ ] UI meets specs

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ricardobrg**
All UIs for CLO Demo app are ready. The Rewards API is defined and is already used in some UIs, but is missing documentation which will be done in another PR. 

Spec is in the left in the screenshots.

## Home Sheet
closes #9
closes #10
closes #11 

Captura de Tela 2023-11-15 às 09 05 43

Captura de Tela 2023-11-15 às 10 59 43

## More Sheet
closes #12 

Captura de Tela 2023-11-15 às 12 31 02

Captura de Tela 2023-11-15 às 14 13 53

## Email account screen
closes #13 

Captura de Tela 2023-11-15 às 18 24 06

Captura de Tela 2023-11-15 às 18 24 36

## Retailer account screen
closes #14 

Captura de Tela 2023-11-15 às 19 06 45
Captura de Tela 2023-11-15 às 19 10 54

### CODE REVIEW

**Comment by sfaria27** [comment]
@ricardobrg the spacing on the "increase earnings" portion of the home sheet still looks a bit strange. is there a way to borrow the format from the "Accounts" section on the More Sheet? This has a box around the icons that seems to make the spacing look more natural.

**Comment by ricardobrg** [comment]
The horizontal margin is wrong (spec is behind)... I will fix it
Captura de Tela 2023-11-16 às 09 44 55

**Comment by ricardobrg** [comment]
@sfaria27 fixed the spacing

Captura de Tela 2023-11-16 às 12 32 34
Captura de Tela 2023-11-16 às 12 32 05

**Comment by sfaria27** [comment]
@ricardobrg on More sheet under what data we collect, please capitalize Cashback Connections

**Comment by ricardobrg** [comment]
@sfaria27 
Captura de Tela 2023-11-17 às 08 41 43

**Review by sfaria27 — APPROVED** [review]
Capitalize Cashback Connections on "Opt out of Cashback Connections"

**Pull request merged**
